version: "0.2"
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - svelte
  - xml
files:
  - "**/.*"
  - "**/*.{css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}"
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
words:
  - Abema
  - Asahi
  - Biglobe
  - Cloudinary
  - FIFA
  - nocheck
  - noninteractive
  - Noto
  - Paravi
  - unspaced
  - VITE
ignoreWords:
  - androidnightly
  - chromeextension
  - dbaeumer
  - dompurify
  - esbenp
  - firefoxextension
  - gorin
  - messageformat
  - opendata
  - postcss
  - pnpm
  - singleline
  - stylelint
  - sveltejs
  - sveltekit
  - topo
  - topojson
  - videomark
  - webdino
  - webm
  - whatsnew
